# Generated by Django 3.1.7 on 2021-04-24 17:28

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
                ('waste_category', models.CharField(choices=[('E Waste', 'E Waste'), ('Paper', 'Paper'), ('Plastic', 'Plastic'), ('Metal', 'Metal'), ('Others', 'Others')], max_length=12)),
                ('waste_quantity', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Completed', 'Completed')], max_length=12)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=dashboard.models.get_upload_path)),
                ('carbon_emission_saved', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company')),
            ],
        ),
    ]
