# Generated by Django 3.0.14 on 2022-07-14 17:43

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_name', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society_location', models.CharField(max_length=300)),
                ('employee_username', models.CharField(max_length=100)),
                ('glass', models.FloatField(blank=True, default=0, null=True)),
                ('paper', models.FloatField(blank=True, default=0, null=True)),
                ('metal', models.FloatField(blank=True, default=0, null=True)),
                ('mix_plastic', models.FloatField(blank=True, default=0, null=True)),
                ('pet_bottles', models.FloatField(blank=True, default=0, null=True)),
                ('mlp_packaging', models.FloatField(blank=True, default=0, null=True)),
                ('tetrapack', models.FloatField(blank=True, default=0, null=True)),
                ('cartons', models.FloatField(blank=True, default=0, null=True)),
                ('e_waste', models.FloatField(blank=True, default=0, null=True)),
                ('hazardous_waste', models.FloatField(blank=True, default=0, null=True)),
                ('other_waste', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Completed', 'Completed')], max_length=12)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=dashboard.models.get_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Company')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateWaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_category', models.CharField(choices=[('E Waste', 'E Waste'), ('Paper', 'Paper'), ('Plastic', 'Plastic'), ('Metal', 'Metal'), ('Others', 'Others')], max_length=12)),
                ('waste_quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('incineration_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('landfill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('recycling_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('carbon_emission_saved', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Update')),
            ],
        ),
    ]
