# Generated by Django 3.0.14 on 2022-07-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='district',
            new_name='city',
        ),
    ]
