# Generated by Django 3.0.14 on 2022-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220714_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='state',
            new_name='employee_name',
        ),
        migrations.AlterField(
            model_name='update',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
