# Generated by Django 3.0.14 on 2022-07-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220714_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='recycling_percentage',
            field=models.IntegerField(null=True),
        ),
    ]
