# Generated by Django 3.0.14 on 2022-07-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_update_recycling_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='district',
            field=models.CharField(default='Maharashtra', max_length=200),
        ),
        migrations.AlterField(
            model_name='update',
            name='city',
            field=models.CharField(default='Mumbai', max_length=200),
        ),
        migrations.AlterField(
            model_name='update',
            name='employee_name',
            field=models.CharField(choices=[('Sharika Dhar', 'Sharika Dhar'), ('Roocha', 'Roocha')], default='Roocha', max_length=200),
        ),
    ]
