# Generated by Django 3.0.14 on 2022-07-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220714_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
