# Generated by Django 3.0.14 on 2022-07-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20220715_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
