# Generated by Django 3.0.14 on 2022-07-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20220715_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='date_of_activity',
            field=models.DateField(null=True),
        ),
    ]
