# Generated by Django 3.0.14 on 2022-07-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_update_date_of_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='date_of_activity',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
