# Generated by Django 3.0.14 on 2022-07-19 00:34

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_company_point_of_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatewaste',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.get_upload_path),
        ),
    ]
