# Generated by Django 3.0.14 on 2022-07-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_updatewaste_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatewaste',
            name='recycling_percentage',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='updatewaste',
            name='status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Completed', 'Completed')], default='Completed', max_length=12),
        ),
    ]
