# Generated by Django 3.0.14 on 2022-07-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20220719_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatewaste',
            name='status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Completed', 'Completed')], default='In Process', max_length=12),
        ),
    ]
