# Generated by Django 3.0.14 on 2022-07-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20220719_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_waste',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
