# Generated by Django 3.0.14 on 2022-07-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_company_total_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='e_waste',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
