# Generated by Django 3.0.14 on 2022-08-01 01:10

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20220723_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.get_upload_path2),
        ),
    ]
