# Generated by Django 3.0.14 on 2022-08-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20220801_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='societycollection',
            name='date_of_activity',
            field=models.DateField(null=True),
        ),
    ]
